/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Cube Guy Character.glb -o src/components/CubeGuy.jsx -r public 
*/
import * as THREE from "three";
import { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useGraph, useThree } from "@react-three/fiber";
import { GLTF, SkeletonUtils } from "three-stdlib";

const MOVEMENT_SPEED = 0.03;
const positionVec = new THREE.Vector3();
export function CubeGuy({ ...props }) {
  const camera = useThree((three) => three.camera);
  const threeScene = useThree((three) => three.scene);
  const directionalLight = threeScene.getObjectByName("directionalLight");
  positionVec.copy(props.position);

  const group = useRef<THREE.Group>(null);

  const { scene, materials, animations } = useGLTF(
    "/models/Cube Guy Character.glb"
  ) as GLTF & { materials: { [key: string]: THREE.MeshStandardMaterial } };

  console.log(scene);
  console.log(materials);

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const objectMap = useGraph(clone);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const nodes = objectMap.nodes as any;
  const [animation, setAnimation] = useState(
    "CharacterArmature|CharacterArmature|CharacterArmature|Idle"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.5).play();
    return () => {
      actions[animation]?.fadeOut(0.5);
    };
  }, [actions, animation]);

  useFrame(() => {
    if (!group.current) return;
    if (group.current.position.distanceTo(props.position) > 0.1) {
      const direction = group.current.position
        .clone()
        .sub(props.position)
        .normalize()
        .multiplyScalar(MOVEMENT_SPEED);
      group.current.position.sub(direction);
      group.current.lookAt(props.position);
      camera.position.set(
        group.current.position.x + 1,
        group.current.position.y + 5,
        group.current.position.z + 5
      );
      directionalLight?.position.set(
        group.current.position.x,
        5,
        group.current.position.z
      );
      directionalLight?.lookAt(group.current.position);
      setAnimation("CharacterArmature|CharacterArmature|CharacterArmature|Run");
    } else {
      setAnimation(
        "CharacterArmature|CharacterArmature|CharacterArmature|Idle"
      );
    }
  });

  console.log(group.current);
  return (
    <group ref={group} {...props} position={positionVec} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            castShadow
            receiveShadow
            name="Character"
            geometry={nodes.Character.geometry}
            material={materials.Atlas}
            skeleton={nodes.Character.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          ></skinnedMesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Cube Guy Character.glb");
