/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Hoodie Character.glb -o src/components/Man.jsx -r public 
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { ThreeEvent, useFrame, useGraph, useThree } from "@react-three/fiber";
import { GLTF, SkeletonUtils } from "three-stdlib";
import { useRecoilState, useRecoilValue } from "recoil";
import {
  CurrentMapAtom,
  CurrentMyRoomPlayerAtom,
  IPlayer,
  MeAtom,
  PlayerGroundStructuresFloorPlaneCornersSelector,
} from "../../../../../store/PlayersAtom";
import { calculateMinimapPosition } from "../../../../../utils";
import gsap from "gsap";

interface IPlayerProps {
  player?: IPlayer;
  position: THREE.Vector3;
}
export function Man({ player, position }: IPlayerProps) {
  const playerId = player?.id;
  const currentMap = useRecoilValue(CurrentMapAtom);
  const [, setCurrentMyRoomPlayer] = useRecoilState(CurrentMyRoomPlayerAtom);
  const playerGroundStructuresFloorPlaneCorners = useRecoilValue(
    PlayerGroundStructuresFloorPlaneCornersSelector
  );

  const memoizedPosition = useMemo(
    () => position,
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );
  const point = document.getElementById(`player-point-${playerId}`);
  const objectInteractionDiv = document.getElementById("object-interaction");

  const playerRef = useRef<THREE.Group>(null);
  const { scene: threeScene } = useThree();
  const nicknameBillboard = threeScene.getObjectByName(
    `nickname-billboard-${playerId}`
  );
  const chatBubbleBoard = threeScene.getObjectByName(
    `chat-bubble-billboard-${playerId}`
  );

  const me = useRecoilValue(MeAtom);

  const { scene, materials, animations } = useGLTF(
    `/models/CubeGuyCharacter.glb`
  ) as GLTF & {
    materials: { [key: string]: THREE.MeshStandardMaterial };
  };

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const clone = useMemo(() => SkeletonUtils.clone(scene), []);
  const objectMap = useGraph(clone);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const nodes = objectMap.nodes as any;

  const [animation, setAnimation] = useState(
    "CharacterArmature|CharacterArmature|CharacterArmature|Idle"
  );
  const { actions } = useAnimations(animations, playerRef);

  useEffect(() => {
    if (!playerRef.current) return;
    if (me?.id === playerId && currentMap === "GROUND") {
      gsap.fromTo(
        playerRef.current.scale,
        {
          duration: 2,
          x: 0,
          y: 0,
          z: 0,
        },
        {
          x: 1,
          y: 1,
          z: 1,
        }
      );
    }
  }, [currentMap, me?.id, nodes, playerId, scene]);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.5).play();
    return () => {
      actions[animation]?.fadeOut(0.5);
    };
  }, [actions, animation]);

  // const clock = new THREE.Clock();

  // const tempVec3 = new THREE.Vector3();

  useFrame(({ camera }) => {
    if (!player) return;
    if (!playerRef.current) return;
    if (playerRef.current.position.distanceTo(position) > 0.1) {
      const direction = playerRef.current.position
        .clone()
        .sub(position)
        .normalize()
        .multiplyScalar(0.04);
      playerRef.current.position.sub(direction);
      playerRef.current.lookAt(position);

      if (point) {
        point.style.transform = `translate(
          ${calculateMinimapPosition(playerRef.current.position).x}px,
          ${calculateMinimapPosition(playerRef.current.position).y}px
          )`;
      }

      setAnimation("CharacterArmature|CharacterArmature|CharacterArmature|Run");
    } else {
      setAnimation(
        "CharacterArmature|CharacterArmature|CharacterArmature|Idle"
      );
    }
    if (nicknameBillboard) {
      nicknameBillboard.position.set(
        playerRef.current.position.x,
        playerRef.current.position.y + 3.5,
        playerRef.current.position.z
      );
      nicknameBillboard.lookAt(10000, 10000, 10000);
    }
    if (chatBubbleBoard) {
      chatBubbleBoard.position.set(
        playerRef.current.position.x,
        playerRef.current.position.y + 4,
        playerRef.current.position.z
      );
      chatBubbleBoard.lookAt(10000, 10000, 10000);
    }

    if (
      me?.id !== undefined &&
      player?.id !== undefined &&
      me?.id === playerId
    ) {
      camera.position.set(
        playerRef.current.position.x + 12,
        playerRef.current.position.y + 12,
        playerRef.current.position.z + 12
      );
      camera.lookAt(playerRef.current.position);

      const currentCloseStructure =
        playerGroundStructuresFloorPlaneCorners.find((structure) => {
          return (
            playerRef.current!.position.x < structure.corners[0].x &&
            playerRef.current!.position.x > structure.corners[2].x &&
            playerRef.current!.position.z < structure.corners[0].z &&
            playerRef.current!.position.z > structure.corners[2].z
          );
        });
      if (currentCloseStructure) {
        if (objectInteractionDiv) {
          objectInteractionDiv.innerText = currentCloseStructure.name;
          objectInteractionDiv.style.display = "block";
          camera.lookAt(currentCloseStructure.position);
          camera.position.set(
            playerRef.current.position.x + 6,
            playerRef.current.position.y + 6,
            playerRef.current.position.z + 6
          );
        }
      } else {
        if (objectInteractionDiv) {
          objectInteractionDiv.innerText = "";
          objectInteractionDiv.style.display = "none";
        }
      }
    }
  });
  return (
    <group
      ref={playerRef}
      position={memoizedPosition}
      name={playerId ?? ""}
      onClick={(e: ThreeEvent<MouseEvent>) => {
        console.log("here?");
        e.stopPropagation();
        if (me?.id !== playerId) {
          setCurrentMyRoomPlayer(player);
        }
      }}
      dispose={null}
    >
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            castShadow
            receiveShadow
            name="Character"
            geometry={nodes.Character.geometry}
            material={materials.Atlas}
            skeleton={nodes.Character.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}
